name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.8
  - numpy
  - pip
  - pip:
    - httpie
    - nbgitpuller
    - sphinx-gallery
    - matplotlib    
    - geopy
    - shapely
    - geographiclib
    - cesiumpy
    - ipyearth
    - git+https://github.com/deeplook/ipyrest
